[package]
name = "wakatime"
version = "0.1.0"
edition = "2024"

[dependencies]
notify = {version = "8.1.0", features = ["serde"]}
rdev = "0.5.3"
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0.98"
tokio = {version="1.47.0",features=["full"]}
